#include <stdio.h>
#include <unistd.h>
#include <signal.h>

void my_signal_interrupt(int sig)
{
  printf("I got signal %d\n", sig);
    // Reset the signal handler to default
  (void) signal(SIGINT, SIG_DFL);
}

int main()
{
  // Set up the signal handler for SIGINT not posix API   not recommanded for production : use sigaction
  // (SIGINT is generated by Ctrl+C)
    (void) signal(SIGINT,my_signal_interrupt);

  while(1) {
      printf("Waiting for interruption...\n");
      sleep(1);
  }
}